version: '3'
services:
  book_store_app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - '8080:8080'
    depends_on:
      - db
    # volumes:
    #   - .:/book_store_app
    #   - /book_store_app/node_modules
    # command: pnpm run start:dev

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_store_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
